[server]
runOnSave = true
fileWatcherType = "auto"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "dark"
primaryColor = "#10b981"
backgroundColor = "#0b0f14"
secondaryBackgroundColor = "#141b24"
textColor = "#f3f4f6"